# Generated by Django 4.0.1 on 2022-03-09 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasNaoContiguas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacaoLocal', models.CharField(max_length=256)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=256)),
                ('nome', models.CharField(max_length=256)),
                ('croqui', models.CharField(max_length=256)),
                ('geolocalizacao', models.CharField(max_length=256)),
                ('municipio', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=2)),
                ('curso_agua', models.CharField(max_length=256)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agriFamiliar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RecHidrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOcupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPosse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecHidrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='croqui',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='teste', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='areaNaoAgricola',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='areasInaproveitaveis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='cursosDAgua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='data',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='lavoutasPermanentes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='lavoutasTemporárias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='participacaoMulher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='pastagens',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='pousio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='silvicultura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='sucessao',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='vegetacaoNativa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
        migrations.AddField(
            model_name='rechidrico',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.questionario'),
        ),
        migrations.AddField(
            model_name='rechidrico',
            name='recHidrico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.tiporechidrico'),
        ),
        migrations.AddField(
            model_name='ocupacao',
            name='ocupacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.tipoocupacao'),
        ),
        migrations.AddField(
            model_name='ocupacao',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.questionario'),
        ),
        migrations.AddField(
            model_name='areasnaocontiguas',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.questionario'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='imovel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema.imovel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='posse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema.tipoposse'),
            preserve_default=False,
        ),
    ]
