# Generated by Django 3.2.9 on 2022-01-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_pessoa_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='titulo',
        ),
    ]
