# Generated by Django 3.2.9 on 2021-11-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empregado')),
            ],
        ),
    ]
