# Generated by Django 3.2.9 on 2021-11-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='name',
            new_name='nome',
        ),
    ]
