# Generated by Django 3.2.9 on 2021-11-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='observacoes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
